name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t jude2001/ms-supplier
      - name: Debug Secrets
        run: |
          echo "Username Secret Length: ${#DOCKERHUB_USERNAME}"
          echo "Password Secret Length: ${#DOCKERHUB_PASSWORD}"
          if [ "${#DOCKERHUB_PASSWORD}" -lt 10 ]; then
            echo "WARNING: Password seems too short to be a token!"
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jude2001
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker push jude2001/ms-supplier:latest
