name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t jude2001/ms-supplier
      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB-USERNAME }}" ]; then
            echo "ERROR: DOCKERHUB-USERNAME is empty!"
          else
            echo "SUCCESS: DOCKERHUB-USERNAME is set."
          fi
          if [ -z "${{ secrets.DOCKERHUB-PASSWORD }}" ]; then
            echo "ERROR: DOCKERHUB-PASSWORD is empty!"
          else
            echo "SUCCESS: DOCKERHUB-PASSWORD is set."
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB-USERNAME }}
          password: ${{ secrets.DOCKERHUB-PASSWORD }}
      - run: docker push jude2001/ms-supplier:latest
